### ISSUE TITLE
Corrupt GPS data after upgrading to "Improved GNSS module initialization" commit

### ISSUE THREAD

**Issue by gyrofx** [stanleyhuangyc/Freematics#186] opened 2023-09-17 20:02 UTC
After using the latest telelogger build (https://github.com/stanleyhuangyc/Freematics/commit/1505b85834847aa0922b6f53effabc757b737b1f) GPS data coming from the device seems corrput.

![image](https://github.com/stanleyhuangyc/Freematics/assets/20068621/95b5edd2-1ee7-45c3-9b91-7b5fc4840f81)

The `date` field is always `000000`, which causes parsing to fail and no GPS data to be sent or recorded.

Without the changes from this commit, everything works as expected.

![image](https://github.com/stanleyhuangyc/Freematics/assets/20068621/3c948ed3-88e4-46a6-ac20-ba17d654ea55)

Device: Freematics One+ Model B (pretty new), internal GPS, WIFI, built with platform.io on Windows

**Comment by canegru** [comment] 2023-09-19 02:30
Confirmed as well, I reverted the commit and it works as expected.

**Comment by stanleyhuangyc** [comment] 2023-10-06 08:16
This commit seems have affect older batch of devices. Will fix this ASAP.

**Comment by stanleyhuangyc** [comment] 2023-10-06 08:29
Avoided M10 GNSS commands from being sent as a workaround.

**Comment by dd310** [comment] 2023-10-06 08:39
> This commit seems have affect older batch of devices. Could you guys confirm the date of purchase of your device?

09/09/23

**Comment by canegru** [comment] 2023-10-06 12:02
> This commit seems have affect older batch of devices. Could you guys confirm the date of purchase of your device?

09/12/23 here

**Comment by gyrofx** [comment] 2023-10-06 19:18
> This commit seems have affect older batch of devices. Could you guys confirm the date of purchase of your device?

07/28/23

**Comment by stanleyhuangyc** [comment] 2023-10-08 00:17
Fixed now. Please try latest commit.
The issue is caused by date value is no longer reported after new GNSS commands sent but date is still checked in the code.

**Comment by stanleyhuangyc** [comment] 2023-10-08 01:12
The issue is fixed now.

The cause:
Recently added m10 configuration commands disable GNSS' RMC command so no date value is reported but date value is checked and non-zero required in the library code.

**Comment by dd310** [comment] 2023-10-11 14:19
Just tried the latest commit and the issue seems indeed solved. Thanks!

**Closed** 2023-10-15 12:11 UTC
